### PR TITLE
Fix large k bug (#11)

### PR DESCRIPTION
**Pull request by ulupo**
As discovered and diagnosed by @ammedmar, `_steenrod_barcode_single_dim` does not work with `k > 1` because it assumes that the birth indices of cohomology representatives are a subset of the simplex indices in one dimension lower than the one in which the reduction is currently happening.

### CODE REVIEW

**Comment by ulupo** [comment]
@ammedmar in the notebook, it says "Notice (below) that the steenrod matrix has only one non-zero column."  I'm not sure I understand.  The Steenrod matrix has many non-zero columns in degree 4.

**Comment by ammedmar** [comment]
Yes, my bad. There are 6 non-zero columns in the Steenrod matrix. So at most there could be 6 Sq^2-bars in degree 4, but there are many more.

**Comment by ulupo** [comment]
I've pushed a fix.  The problem was that I was forgetting to ensure that all remaining Steenrod columns are reduced at the very last iteration in the outer for loop.  Please check!

**Comment by ammedmar** [comment]
Unfortunately, it did not fix all problems. I added more examples to the *cp2* notebook. There are still weird infinite Sq^2-bars.

**Review by ammedmar — APPROVED** [review]
Looks good to me

**Comment by ulupo** [comment]
Great!  OK if I remove all the debugging material (notebooks, data) from this PR?

**Comment by ammedmar** [comment]
Yes :-)

**Pull request merged**
