### PR TITLE
notebooks

### PR DESCRIPTION
**Pull request by ammedmar**

### CODE REVIEW

**Comment by ammedmar** [comment]
Adding the data and notebooks needed for the following examples: rp2, rp3 rp4, cone on those, cp2, s2s4 and suspension of those.

**Comment by ulupo** [comment]
@gtauzin what do you think about the addition of pickle files that is being proposed here?  Should we insist on not using binary files and use e.g. a JSON format, or trust that these files won't be changed and we don't have to worry about it?

**Comment by ammedmar** [comment]
I removed the pickle files replacing the data with generating functions in the examples.py file

**Review by ulupo — APPROVED** [review]
LGTM!  Great work with the new examples file in `notebooks`.

**Comment by gtauzin** [comment]
I think it's great!

What I would like to offer is to put those functions in the example file in the library. Maybe separate it into a utils file and dataset file so that their documentation is also available on the package documentation. 

(it would be great to improve the docs of the function by adding a parameters and a returns field)

**Comment by ammedmar** [comment]
I added more details to the examples docstrings, split the basic data to a separate file and remove wildcard imports as requested in #17.

**Review by gtauzin — APPROVED** [review]
Lgtm. It's not exactly what I meant for the file splitting, but I can make a proposal myself.

**Pull request merged**
